nodeLinker: node-modules

enableGlobalCache: true

yarnPath: .yarn/releases/yarn-4.0.2.cjs

packageExtensions:
  react-dom@*:
    peerDependencies:
      react: "*"

compressedResolutions: true

enableImmutableInstalls: true

defaultSemverRangePrefix: "^"

pnpMode: "loose"

enableStrictSettings: true