import { Page, Locator, expect } from '@playwright/test'

export class HeavyPage {
  readonly page: Page
  readonly queryInput: Locator
  readonly numAgentsInput: Locator
  readonly executeButton: Locator
  readonly orchestrateTab: Locator
  readonly toolsTab: Locator
  readonly configTab: Locator
  readonly resultsTab: Locator
  readonly agentProgress: Locator
  readonly executionResults: Locator
  readonly loadingSpinner: Locator

  constructor(page: Page) {
    this.page = page
    this.queryInput = page.locator('[data-testid="heavy-query-input"]')
    this.numAgentsInput = page.locator('[data-testid="heavy-agents-input"]')
    this.executeButton = page.locator('[data-testid="heavy-execute-button"]')
    this.orchestrateTab = page.locator('[data-testid="tab-orchestrate"]')
    this.toolsTab = page.locator('[data-testid="tab-tools"]')
    this.configTab = page.locator('[data-testid="tab-config"]')
    this.resultsTab = page.locator('[data-testid="tab-results"]')
    this.agentProgress = page.locator('[data-testid="agent-progress"]')
    this.executionResults = page.locator('[data-testid="execution-results"]')
    this.loadingSpinner = page.locator('[data-testid="loading-spinner"]')
  }

  async goto() {
    await this.page.goto('/heavy')
  }

  async setQuery(query: string) {
    await this.queryInput.fill(query)
  }

  async setNumAgents(numAgents: number) {
    await this.numAgentsInput.fill(numAgents.toString())
  }

  async executeTask(query?: string, numAgents?: number) {
    if (query) await this.setQuery(query)
    if (numAgents) await this.setNumAgents(numAgents)
    
    await this.executeButton.click()
  }

  async waitForExecution() {
    await expect(this.loadingSpinner).toBeVisible()
    await expect(this.loadingSpinner).toBeHidden({ timeout: 30000 })
  }

  async expectExecutionComplete() {
    await expect(this.resultsTab).toBeVisible()
    await this.resultsTab.click()
    await expect(this.executionResults).toBeVisible()
  }

  async expectAgentProgress() {
    await expect(this.agentProgress).toBeVisible()
    // Check for agent status indicators
    await expect(this.page.locator('[data-testid*="agent-status"]')).toBeVisible()
  }

  async switchToTab(tabName: 'orchestrate' | 'tools' | 'config' | 'results') {
    const tab = this.page.locator(`[data-testid="tab-${tabName}"]`)
    await tab.click()
  }

  async expectToolsVisible() {
    await this.switchToTab('tools')
    await expect(this.page.locator('[data-testid="tool-card"]')).toHaveCount(2)
  }

  async expectConfigVisible() {
    await this.switchToTab('config')
    await expect(this.numAgentsInput).toBeVisible()
  }

  async updateConfig(numAgents: number) {
    await this.switchToTab('config')
    await this.setNumAgents(numAgents)
    await this.page.locator('[data-testid="update-config-button"]').click()
  }

  async expectResultsWithAgents(expectedAgents: number) {
    await this.switchToTab('results')
    await expect(this.executionResults).toContainText(`Generated by ${expectedAgents} agents`)
  }

  async expectToBeOnHeavyPage() {
    await expect(this.page).toHaveURL('/heavy')
    await expect(this.queryInput).toBeVisible()
  }
}