import { APIRequestContext, BrowserContext } from '@playwright/test'
import express from 'express'
import cors from 'cors'

let mockServer: any = null
let mockServerPort = 3001

/**
 * Start a mock API server for testing
 */
export async function startMockServer(): Promise<void> {
  if (mockServer) return
  
  const app = express()
  app.use(cors())
  app.use(express.json())
  
  // Mock authentication endpoints
  app.post('/api/auth/login', async (req, res) => {
    const { email, password } = req.body
    
    // Demo credentials
    if (email === 'demo@crazy-gary.ai' && password === 'demo123') {
      res.json({
        success: true,
        user: {
          id: 'demo',
          email: 'demo@crazy-gary.ai',
          name: 'Demo User',
          role: 'admin'
        },
        token: 'demo-token'
      })
    } else {
      res.status(401).json({
        success: false,
        error: 'Invalid credentials'
      })
    }
  })
  
  app.post('/api/auth/register', async (req, res) => {
    const { name, email, password } = req.body
    
    if (email && password && name) {
      res.json({
        success: true,
        user: {
          id: 'test-user',
          email,
          name,
          role: 'user'
        },
        token: 'test-token'
      })
    } else {
      res.status(400).json({
        success: false,
        error: 'Missing required fields'
      })
    }
  })
  
  app.get('/api/auth/validate', async (req, res) => {
    const token = req.headers.authorization?.replace('Bearer ', '')
    
    if (token === 'demo-token' || token === 'test-token') {
      res.json({
        valid: true,
        user: {
          id: 'demo',
          email: 'demo@crazy-gary.ai',
          name: 'Demo User',
          role: 'admin'
        }
      })
    } else {
      res.json({ valid: false })
    }
  })
  
  // Mock heavy orchestration endpoints
  app.get('/api/heavy/config', async (req, res) => {
    res.json({
      num_agents: 4,
      task_timeout: 30,
      features: {
        parallel_processing: true,
        error_recovery: true,
        progress_tracking: true
      }
    })
  })
  
  app.get('/api/heavy/tools', async (req, res) => {
    res.json({
      web_search: {
        name: 'Web Search',
        description: 'Search the web for information',
        parameters: {
          properties: {
            query: { type: 'string' },
            num_results: { type: 'number' }
          }
        }
      },
      data_analysis: {
        name: 'Data Analysis',
        description: 'Analyze data and generate insights',
        parameters: {
          properties: {
            dataset: { type: 'string' },
            analysis_type: { type: 'string' }
          }
        }
      }
    })
  })
  
  app.post('/api/heavy/orchestrate', async (req, res) => {
    const { query, num_agents } = req.body
    
    // Simulate processing delay
    setTimeout(() => {
      res.json({
        success: true,
        response: `Comprehensive analysis of: "${query}"\n\nThis analysis was generated by ${num_agents} AI agents working in parallel. The results show comprehensive insights across multiple dimensions.`,
        metadata: {
          num_agents,
          successful_agents: num_agents,
          total_tokens: Math.floor(Math.random() * 1000) + 500
        },
        execution_time: 2.5,
        synthesis_time: 0.8,
        agents: Array.from({ length: num_agents }, (_, i) => ({
          agent_id: i + 1,
          status: 'completed',
          question: `Analyze "${query}" from perspective ${i + 1}`,
          result: `Agent ${i + 1} analysis: Detailed insights on "${query}" from a unique perspective.`,
          execution_time: Math.random() * 2 + 1
        }))
      })
    }, 1000)
  })
  
  app.get('/api/heavy/progress', async (req, res) => {
    res.json({
      agent_progress: {
        '1': 'completed',
        '2': 'completed',
        '3': 'processing',
        '4': 'completed'
      }
    })
  })
  
  // Mock task management endpoints
  app.get('/api/tasks', async (req, res) => {
    res.json({
      tasks: [
        {
          id: 'task-1',
          title: 'Test Task 1',
          description: 'This is a test task',
          status: 'pending',
          created_at: new Date().toISOString()
        },
        {
          id: 'task-2',
          title: 'Test Task 2',
          description: 'Another test task',
          status: 'completed',
          created_at: new Date().toISOString()
        }
      ]
    })
  })
  
  app.post('/api/tasks', async (req, res) => {
    const { title, description } = req.body
    res.json({
      task: {
        id: `task-${Date.now()}`,
        title,
        description,
        status: 'pending',
        created_at: new Date().toISOString()
      }
    })
  })
  
  // Start the server
  await new Promise<void>((resolve, reject) => {
    mockServer = app.listen(mockServerPort, (err: any) => {
      if (err) {
        reject(err)
      } else {
        console.log(`Mock server running on port ${mockServerPort}`)
        resolve()
      }
    })
  })
}

/**
 * Stop the mock API server
 */
export async function stopMockServer(): Promise<void> {
  if (mockServer) {
    await new Promise<void>((resolve) => {
      mockServer.close(() => {
        mockServer = null
        console.log('Mock server stopped')
        resolve()
      })
    })
  }
}

/**
 * Set up test data for E2E tests
 */
export async function setupTestData(): Promise<void> {
  console.log('📊 Setting up test data...')
  
  // Set up localStorage test data
  // This will be used by tests to set up initial state
  global.testData = {
    users: {
      demo: {
        id: 'demo',
        email: 'demo@crazy-gary.ai',
        name: 'Demo User',
        role: 'admin'
      }
    },
    tasks: [
      {
        id: 'test-task-1',
        title: 'Sample Task',
        description: 'This is a sample task for testing',
        status: 'pending'
      }
    ],
    heavyConfig: {
      num_agents: 4,
      task_timeout: 30
    }
  }
}

/**
 * Clean up test data
 */
export async function cleanupTestData(): Promise<void> {
  console.log('🧹 Cleaning up test data...')
  
  // Clean up global test data
  delete global.testData
}

/**
 * Helper function to wait for network idle
 */
export async function waitForNetworkIdle(page: any, timeout = 5000): Promise<void> {
  await page.waitForLoadState('networkidle', { timeout })
}

/**
 * Helper function to set demo mode in localStorage
 */
export async function setDemoMode(page: any): Promise<void> {
  await page.evaluate(() => {
    localStorage.setItem('demo_mode', 'true')
    localStorage.setItem('auth_token', 'demo-token')
  })
}

/**
 * Helper function to clear localStorage
 */
export async function clearLocalStorage(page: any): Promise<void> {
  await page.evaluate(() => {
    localStorage.clear()
  })
}

/**
 * Create a test user account
 */
export async function createTestUser(request: APIRequestContext, email: string, password: string, name: string) {
  const response = await request.post('/api/auth/register', {
    data: { email, password, name }
  })
  return response.json()
}

/**
 * Login with test credentials
 */
export async function loginTestUser(page: any, email: string, password: string) {
  await page.goto('/login')
  await page.fill('[data-testid="email-input"]', email)
  await page.fill('[data-testid="password-input"]', password)
  await page.click('[data-testid="login-button"]')
  await page.waitForURL('/dashboard')
}